version: '3.9'

networks:
  app:
    driver: bridge

services:
  backend:
    container_name: backend
    build:
      context: ./frontend
      dockerfile: ./Containerfile.dev
    stdin_open: true
    restart: on-failure
    environment:
      CHOKIDAR_USEPOLLING: true
      DANGEROUSLY_DISABLE_HOST_CHECK: true
    networks:
      - app
    ports:
      - 5757:5757
    volumes:
      - be_modules:/var/www/backend/node_modules
      - ./src:/var/www/backend/src
      - ./public:/var/www/backend/public

volumes:
  be_node_modules:
